[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = picosdk

board_build.core = earlephilhower

build_flags =
    -std=gnu++2a

monitor_speed = 115200
